# Machine Learning Algorithm using Movie Reviews

 1. Naive bayes

 2. Logistic Regression

 3. Support Vector machines

## Importing required libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import  confusion_matrix

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.tokenize import word_tokenize  
from sklearn.linear_model import LogisticRegression
from sklearn import svm

In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


## Data Cleaning

In [31]:
df_Negative=pd.read_csv("/content/drive/My Drive/Bert-single/MovieReviews/-ve.csv")

In [32]:
df_Negative

Text
0      plot : two teen couples go to a church party ,...
1                           they get into an accident . 
2      one of the guys dies , but his girlfriend cont...
3                                     what's the deal ? 
4          watch the movie and " sorta " find out . . . 
...                                                  ...
31377               i can't blame the actors , though . 
31378  it's not their fault they had a cruddy script ...
31379  this concludes rydain's diatribe on a shameles...
31380                      comments , flames , anyone ? 
31381  -rydain the atomic cheese , fresh from chernob...

[31382 rows x 1 columns]

In [33]:
df_Negative['Sentiment']=0

In [34]:
df_Negative

Text  Sentiment
0      plot : two teen couples go to a church party ,...          0
1                           they get into an accident .           0
2      one of the guys dies , but his girlfriend cont...          0
3                                     what's the deal ?           0
4          watch the movie and " sorta " find out . . .           0
...                                                  ...        ...
31377               i can't blame the actors , though .           0
31378  it's not their fault they had a cruddy script ...          0
31379  this concludes rydain's diatribe on a shameles...          0
31380                      comments , flames , anyone ?           0
31381  -rydain the atomic cheese , fresh from chernob...          0

[31382 rows x 2 columns]

In [35]:
df_positive=pd.read_csv("/content/drive/My Drive/Bert-single/MovieReviews/+ve.csv")

In [36]:
df_positive['Sentiment']=1

In [37]:
df_positive

Text  Unnamed: 1  Sentiment
0      films adapted from comic books have had plenty...         NaN          1
1      for starters , it was created by alan moore ( ...         NaN          1
2      to say moore and campbell thoroughly researche...         NaN          1
3      the book ( or " graphic novel , " if you will ...         NaN          1
4      in other words , don't dismiss this film becau...         NaN          1
...                                                  ...         ...        ...
32486  although many of the characters are stuck in a...         NaN          1
32487  the character of dominique ( anh duong ) , the...         NaN          1
32488  and the one sex scene in the film was beautifu...         NaN          1
32489  for once , it did not invlove steaminess , or ...         NaN          1
32490   " high art , " which won the screenwriting aw...         NaN          1

[32491 rows x 3 columns]

In [38]:
del df_positive['Unnamed: 1']
df_positive

Text  Sentiment
0      films adapted from comic books have had plenty...          1
1      for starters , it was created by alan moore ( ...          1
2      to say moore and campbell thoroughly researche...          1
3      the book ( or " graphic novel , " if you will ...          1
4      in other words , don't dismiss this film becau...          1
...                                                  ...        ...
32486  although many of the characters are stuck in a...          1
32487  the character of dominique ( anh duong ) , the...          1
32488  and the one sex scene in the film was beautifu...          1
32489  for once , it did not invlove steaminess , or ...          1
32490   " high art , " which won the screenwriting aw...          1

[32491 rows x 2 columns]

In [39]:
Sentiment=[df_Negative,df_positive]
Final_data=pd.concat(Sentiment)

In [40]:
Final_data.columns=['Sentence','Sentiment']

In [41]:
Final_data

Sentence  Sentiment
0      plot : two teen couples go to a church party ,...          0
1                           they get into an accident .           0
2      one of the guys dies , but his girlfriend cont...          0
3                                     what's the deal ?           0
4          watch the movie and " sorta " find out . . .           0
...                                                  ...        ...
32486  although many of the characters are stuck in a...          1
32487  the character of dominique ( anh duong ) , the...          1
32488  and the one sex scene in the film was beautifu...          1
32489  for once , it did not invlove steaminess , or ...          1
32490   " high art , " which won the screenwriting aw...          1

[63873 rows x 2 columns]

In [42]:
import string 
result = string.punctuation 
print(result)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [43]:
Final_data['Cleaned sentence']=Final_data['Sentence'].str.replace('[{}]'.format(result), '')

In [44]:
Final_data

Sentence  ...                                   Cleaned sentence
0      plot : two teen couples go to a church party ,...  ...  plot  two teen couples go to a church party  d...
1                           they get into an accident .   ...                        they get into an accident  
2      one of the guys dies , but his girlfriend cont...  ...  one of the guys dies  but his girlfriend conti...
3                                     what's the deal ?   ...                                   whats the deal  
4          watch the movie and " sorta " find out . . .   ...           watch the movie and  sorta  find out    
...                                                  ...  ...                                                ...
32486  although many of the characters are stuck in a...  ...  although many of the characters are stuck in a...
32487  the character of dominique ( anh duong ) , the...  ...  the character of dominique  anh duong   the  f...
32488  and the one sex scene in the film was beautifu...  ...  and the one sex scene in the film was beautifu...
32489  for once , it did not invlove steaminess , or ...  ...  for once  it did not invlove steaminess  or vi...
32490   " high art , " which won the screenwriting aw...  ...    high art   which won the screenwriting award...

[63873 rows x 3 columns]

In [45]:
Final_data.head(20)

Sentence  ...                                   Cleaned sentence
0   plot : two teen couples go to a church party ,...  ...  plot  two teen couples go to a church party  d...
1                        they get into an accident .   ...                        they get into an accident  
2   one of the guys dies , but his girlfriend cont...  ...  one of the guys dies  but his girlfriend conti...
3                                  what's the deal ?   ...                                   whats the deal  
4       watch the movie and " sorta " find out . . .   ...           watch the movie and  sorta  find out    
5   critique : a mind-fuck movie for the teen gene...  ...  critique  a mindfuck movie for the teen genera...
6   which is what makes this review an even harder...  ...  which is what makes this review an even harder...
7   they seem to have taken this pretty neat conce...  ...  they seem to have taken this pretty neat conce...
8          so what are the problems with the movie ?   ...          so what are the problems with the movie  
9   well , its main problem is that it's simply to...  ...  well  its main problem is that its simply too ...
10  it starts off " normal " but then downshifts i...  ...  it starts off  normal  but then downshifts int...
11  there are dreams , there are characters coming...  ...  there are dreams  there are characters coming ...
12  now i personally don't mind trying to unravel ...  ...  now i personally dont mind trying to unravel a...
13  it's obviously got this big secret to hide , b...  ...  its obviously got this big secret to hide  but...
14  and do they make things entertaining , thrilli...  ...  and do they make things entertaining  thrillin...
15                                      not really .   ...                                       not really  
16  the sad part is that the arrow and i both dig ...  ...  the sad part is that the arrow and i both dig ...
17  i guess the bottom line with movies like this ...  ...  i guess the bottom line with movies like this ...
18  i mean , showing melissa sagemiller running aw...  ...  i mean  showing melissa sagemiller running awa...
19                      okay , we get it . . . there   ...                          okay  we get it    there 

[20 rows x 3 columns]

In [46]:
Final_data=Final_data.drop('Sentence',axis=1)

In [47]:
Final_data

Sentiment                                   Cleaned sentence
0              0  plot  two teen couples go to a church party  d...
1              0                        they get into an accident  
2              0  one of the guys dies  but his girlfriend conti...
3              0                                   whats the deal  
4              0           watch the movie and  sorta  find out    
...          ...                                                ...
32486          1  although many of the characters are stuck in a...
32487          1  the character of dominique  anh duong   the  f...
32488          1  and the one sex scene in the film was beautifu...
32489          1  for once  it did not invlove steaminess  or vi...
32490          1    high art   which won the screenwriting award...

[63873 rows x 2 columns]

## Building the model

In [ ]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# stopword=nltk.corpus.stopwords.words('english')
# stopword[:5]

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
tfidf = TfidfVectorizer()
Model_1 = tfidf.fit_transform(Final_data['Cleaned sentence'])

In [ ]:
Model_1

<63873x47260 sparse matrix of type '<class 'numpy.float64'>'
	with 1123508 stored elements in Compressed Sparse Row format>

In [ ]:
# train test split for final_reviews
X_train, X_test, y_train, y_test = train_test_split(Model_1, Final_data['Sentiment'], test_size=0.25, random_state=70)

### 1. Naive bayes

In [48]:
MNB = MultinomialNB()
MNB.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [49]:
predicted_train = MNB.predict(X_train)
predicted_train

array([0, 0, 0, ..., 0, 1, 0])

In [50]:
print("The accuracy score of train data {0}".format(accuracy_score(predicted_train, y_train)))
predicted_test= MNB.predict(X_test)
print("The accuracy score of test data {0}".format(accuracy_score(predicted_test, y_test)))
print("The ROC AUC score on test data {0}".format(roc_auc_score(predicted_test, y_test)))
print("---------------confusion matrix------------")
print(confusion_matrix(predicted_test, y_test))


The accuracy score of train data 0.8249832999331997
The accuracy score of test data 0.7044273279478991
The ROC AUC score on test data 0.7046445539239068
---------------confusion matrix------------
[[5258 2171]
 [2549 5991]]


### 2. Logistic regression

In [ ]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
log_predicted_train = logreg.predict(X_train)
log_predicted_test= logreg.predict(X_test)

In [ ]:
print("The accuracy score of train data {0}".format(accuracy_score(log_predicted_train, y_train)))
print("The accuracy score of test data {0}".format(accuracy_score(log_predicted_test, y_test)))
print("The ROC AUC score on test data {0}".format(roc_auc_score(log_predicted_test, y_test)))
print("---------------confusion matrix------------")
print(confusion_matrix(log_predicted_test, y_test))

The accuracy score of train data 0.7995365731462926
The accuracy score of test data 0.6859540359446428
The ROC AUC score on test data 0.6857889116783373
---------------confusion matrix------------
[[5259 2467]
 [2548 5695]]


### 3. Support Vector Machines

In [ ]:
log_predicted_train = classifier_linear.predict(X_train)
log_predicted_test= classifier_linear.predict(X_test)

In [ ]:
print("The accuracy score of train data {0}".format(accuracy_score(log_predicted_train, y_train)))
print("The accuracy score of test data {0}".format(accuracy_score(log_predicted_test, y_test)))
print("The ROC AUC score on test data {0}".format(roc_auc_score(log_predicted_test, y_test)))
print("---------------confusion matrix------------")
print(confusion_matrix(log_predicted_test, y_test))

The accuracy score of train data 0.8290956913827655
The accuracy score of test data 0.6925292754712254
The ROC AUC score on test data 0.6924744316689848
---------------confusion matrix------------
[[5419 2522]
 [2388 5640]]
